version: '2'
services:
    asia-app:
        image: asia
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://asia-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=asia
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=asia-elasticsearch:9300
        ports:
            - 8080:8080
    asia-mongodb:
        extends:
            file: mongodb.yml
            service: asia-mongodb
    asia-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: asia-elasticsearch
